/* _jsscan.cjs — a JavaScript source walker that knows strings, templates,
   comments and regex literals apart.
 *
 * WHY THIS IS SHARED
 * ------------------
 * Three separate guards in this repository have been written with a line regex
 * or a hand-rolled state machine, and all three were wrong in the same way:
 *
 *   1. The <style> scanner in csp.test.cjs reported 10 sites where there were
 *      11 — the eleventh sat inside a multi-line template literal, and a later
 *      version lost two more because `.replace(/"/g, '&quot;')` looks like a
 *      quote opening a string unless you can tell a regex from a division.
 *   2. A TypeScript stripper written for rate-limit-outage.test.cjs rewrote
 *      `{ degraded: why }` into `{ degraded }`. It still PARSED, so the "does
 *      it parse" guard passed, and every assertion after it ran against a
 *      module unlike the deployed one.
 *   3. A comment stripper written for checked-mutations.test.cjs desynced on
 *      the first regex literal containing a quote and silently stopped
 *      stripping, which surfaced a comment as if it were code.
 *
 * The lesson each time is the same: a guard that mis-parses does not fail
 * loudly, it blesses whatever it could not see. So there is now ONE walker,
 * with fixtures, and the guards call it.
 *
 * Telling a regex from a division needs the standard heuristic: a '/' begins a
 * regex when the previous meaningful character cannot end an expression. That
 * is not a full JavaScript parse and does not pretend to be; the fixtures in
 * _jsscan.test.cjs are the ground truth for what it does handle.
 */

const BEFORE_REGEX = new Set([
  '(', ',', '=', ':', '[', '!', '&', '|', '?', '{', '}', ';',
  '+', '-', '*', '%', '<', '>', '~', '^', null,
]);

/**
 * Walk `src`, calling back at every character with what it is.
 *
 * @param {string} src
 * @param {(ch: string, at: number, kind: 'code'|'string'|'comment') => void} visit
 */
function walk(src, visit) {
  let i = 0, quote = null, comment = null, prev = null;
  while (i < src.length) {
    const c = src[i], next = src[i + 1];

    if (comment) {
      visit(c, i, 'comment');
      if (comment === 'line' && c === '\n') comment = null;
      else if (comment === 'block' && c === '*' && next === '/') { comment = null; visit(next, i + 1, 'comment'); i++; }
      i++;
      continue;
    }

    if (quote) {
      // Strings are consumed before comments on purpose: an accept="/*,.pdf"
      // attribute once opened a phantom block comment and blinded a scan for
      // 519 lines.
      if (c === '\\') { visit(c, i, 'string'); visit(src[i + 1], i + 1, 'string'); i += 2; continue; }
      visit(c, i, 'string');
      if (c === quote) quote = null;
      i++;
      continue;
    }

    if (c === '/' && next === '/') { comment = 'line'; visit(c, i, 'comment'); visit(next, i + 1, 'comment'); i += 2; continue; }
    if (c === '/' && next === '*') { comment = 'block'; visit(c, i, 'comment'); visit(next, i + 1, 'comment'); i += 2; continue; }

    if (c === '/' && BEFORE_REGEX.has(prev)) {          // regex literal — skip it
      visit(c, i, 'code');
      i++;
      while (i < src.length) {
        if (src[i] === '\\') { visit(src[i], i, 'code'); visit(src[i + 1], i + 1, 'code'); i += 2; continue; }
        if (src[i] === '[') {
          while (i < src.length && src[i] !== ']') {
            if (src[i] === '\\') { visit(src[i], i, 'code'); i++; }
            visit(src[i], i, 'code');
            i++;
          }
        }
        if (src[i] === '/' || src[i] === '\n') break;
        visit(src[i], i, 'code');
        i++;
      }
      if (i < src.length) visit(src[i], i, 'code');
      i++;
      prev = '/';
      continue;
    }

    if (c === '"' || c === "'" || c === '`') { quote = c; visit(c, i, 'string'); i++; continue; }
    visit(c, i, 'code');
    if (!/\s/.test(c)) prev = c;
    i++;
  }
}

/**
 * Return `src` with every comment character replaced by a space, preserving
 * length, line count and every offset. Strings and regex literals are left
 * exactly as they are.
 */
function blankComments(src) {
  const out = src.split('');
  walk(src, (ch, at, kind) => {
    if (kind === 'comment' && ch !== '\n') out[at] = ' ';
  });
  return out.join('');
}

/**
 * Offsets at which `needle` appears inside a string or template literal.
 * This is what finds HTML generated by concatenation.
 */
function findInStrings(src, needle) {
  const hits = [];
  walk(src, (ch, at, kind) => {
    if (kind === 'string' && src.startsWith(needle, at)) hits.push(at);
  });
  return hits;
}

/** 1-based line number for a character offset. */
function lineAt(src, offset) {
  return src.slice(0, offset).split('\n').length;
}

module.exports = { walk, blankComments, findInStrings, lineAt, BEFORE_REGEX };
