#!/usr/bin/env bash
# check-db-drift.sh — fail when production authorization state stops matching
# what the repository says it should be.
#
# WHY THIS EXISTS
# ---------------
# GL-DRIFT-01. Migration-only review cannot prove production state. Three
# separate holes in this codebase were invisible to it:
#
#   * 2026-05-18 — fourteen permissive `anon` policies applied by hand in the
#     dashboard, present in no migration. Every table readable and deletable by
#     anyone on the internet.
#   * 2026-08-28 — `authed all` / `anon read` / `public read` on thirteen
#     tables, likewise in no migration.
#   * 2026-08-29 — anon holding INSERT/UPDATE/DELETE/TRUNCATE on 73 tables.
#
# All three were found by querying the live catalog. So this diffs the live
# catalog against a committed baseline, and fails on any unreviewed change.
#
# USAGE
#   bash scripts/check-db-drift.sh            # compare, fail on drift
#   bash scripts/check-db-drift.sh --update   # rewrite the baseline
#
# --update is for AFTER a reviewed migration changes authorization on purpose:
# apply the migration, run --update, and commit the baseline WITH that
# migration, so the diff is reviewed as part of the same PR.
#
# Requires SUPABASE_ACCESS_TOKEN. It is read from the environment, sent only as
# a request header, and never echoed. In CI it is supplied by the workflow.

set -uo pipefail

PROJECT_REF="ufjkeqmxwuyhbqyugcgg"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
QUERY_FILE="$ROOT/scripts/db-drift-snapshot.sql"
BASELINE="$ROOT/docs/database/authorization-baseline.txt"
MODE="${1:-check}"

if [ ! -f "$QUERY_FILE" ]; then
  echo "missing $QUERY_FILE" >&2; exit 2
fi
if [ -z "${SUPABASE_ACCESS_TOKEN:-}" ]; then
  echo "SUPABASE_ACCESS_TOKEN is not set — cannot read production state." >&2
  echo "This is a FAILURE, not a skip: an unverifiable drift check is worth nothing." >&2
  exit 1
fi

# jq on CI runners, node otherwise, so this runs in Git Bash too.
if command -v jq >/dev/null 2>&1;     then JT=jq
elif command -v node >/dev/null 2>&1; then JT=node
else echo "need jq or node to build/parse JSON" >&2; exit 1; fi

wrap_query() {
  if [ "$JT" = "jq" ]; then jq -Rs '{query: .}' < "$1"
  else node -e 'const fs=require("fs");process.stdout.write(JSON.stringify({query:fs.readFileSync(process.argv[1],"utf8")}))' "$1"
  fi
}

resp=$(curl -sS --max-time 60 -X POST \
  "https://api.supabase.com/v1/projects/$PROJECT_REF/database/query" \
  -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" \
  -H "Content-Type: application/json" \
  --data "$(wrap_query "$QUERY_FILE")")

# Extract the `line` field from each row, in the order the query returned them.
if [ "$JT" = "jq" ]; then
  current=$(printf '%s' "$resp" | jq -r '.[].line' 2>/dev/null)
else
  current=$(printf '%s' "$resp" | node -e '
    let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{
      try{ const j=JSON.parse(s);
        if(!Array.isArray(j)){ process.exit(3); }
        process.stdout.write(j.map(r=>r.line).join("\n"));
      }catch(e){ process.exit(3); }
    });')
fi

if [ -z "$current" ]; then
  echo "Could not read the authorization snapshot from production." >&2
  echo "Response head: $(printf '%s' "$resp" | head -c 300)" >&2
  exit 1
fi

if [ "$MODE" = "--update" ]; then
  mkdir -p "$(dirname "$BASELINE")"
  {
    echo "# Authorization baseline — generated by scripts/check-db-drift.sh --update"
    echo "# Do not hand-edit. Regenerate after a reviewed migration and commit it"
    echo "# alongside that migration, so the diff is reviewed with the change."
    echo "#"
    echo "# Each line is one authorization fact: a policy, an RLS flag, a table"
    echo "# grant, a function's security mode/search_path/ACL, or a storage bucket."
    printf '%s\n' "$current"
  } > "$BASELINE"
  echo "baseline updated: $(printf '%s\n' "$current" | wc -l | tr -d ' ') facts -> $BASELINE"
  exit 0
fi

if [ ! -f "$BASELINE" ]; then
  echo "No baseline at $BASELINE. Create one with: bash scripts/check-db-drift.sh --update" >&2
  exit 1
fi

expected=$(grep -v '^#' "$BASELINE")

if [ "$current" = "$expected" ]; then
  echo "No authorization drift. $(printf '%s\n' "$current" | wc -l | tr -d ' ') facts match the baseline."
  exit 0
fi

echo
echo "AUTHORIZATION DRIFT DETECTED"
echo "Production no longer matches docs/database/authorization-baseline.txt."
echo
echo "  '-' = in the baseline but NOT in production (something was removed)"
echo "  '+' = in production but NOT in the baseline (something was added —"
echo "        if this was not a reviewed migration, it is dashboard drift)"
echo
diff <(printf '%s\n' "$expected") <(printf '%s\n' "$current") \
  | grep -E '^[<>]' \
  | sed -e 's/^</  - /' -e 's/^>/  + /' \
  | head -60
echo
n=$(diff <(printf '%s\n' "$expected") <(printf '%s\n' "$current") | grep -cE '^[<>]')
[ "$n" -gt 60 ] && echo "  ... and $((n - 60)) more"
echo
echo "If this change was intended and reviewed: apply the migration, run"
echo "  bash scripts/check-db-drift.sh --update"
echo "and commit the baseline in the SAME pull request as the migration."
echo
echo "If it was NOT: someone changed production outside the repository."
echo "CLAUDE.md rule 2 — never change database permissions through the dashboard."
exit 1
